### PR TITLE
Create in_code_documentation_guidelines.md

### LINKED ISSUE #32: document code with JSDoc-style block comments
I'm a fan of [JSDoc](http://usejsdoc.org/about-getting-started.html)-style documentation comments, since it's usually helpful to comprehensively document your module/function APIs (while the implementation itself should be self-documented, unless you're doing something quite clever). We won't be using the jsdoc utility to actually generate documentation, but I think it's a decent format to adhere to. I only typically use `@param` and `@return` tags, like in this verbose example:

```javascript
/**
 * Import all OpenAddresses CSV files in a directory into Pelias elasticsearch.
 *
 * @param {string} dirPath The path to a directory. All *.csv files inside of
 *    it will be read and imported (they're assumed to contain OpenAddresses
 *    data).
 * @param {object} opts Options to configure the import. Supports the following
 *    keys:
 *
 *      deduplicate: Pass address object through `address-deduplicator-stream`
 *        to perform deduplication. See the documentation:
 *        https://github.com/pelias/address-deduplicator-stream
 *
 *      admin-values: Add admin values to each address object (since
 *        OpenAddresses doesn't contain any) using `hierarchy-lookup`. See the
 *        documentation: https://github.com/pelias/hierarchy-lookup
 */
```

I'll eschew it for short/obvious functions.

Thoughts from @pelias/contributors ?

### PR DESCRIPTION
**Pull request by dianashk**
Fixes #32

### CODE REVIEW

**Comment by dianashk** [comment]
@pelias/contributors did I miss anything?

**Comment by sevko** [comment]
Would it make sense to move this into `CONTRIBUTING.md`, under/around the [project standards](https://github.com/pelias/pelias/blob/master/CONTRIBUTING.md#project-standards-overview) section?

**Comment by sevko** [comment]
Any thoughts on the above?

**Comment by dianashk** [comment]
Since we're planning to overhaul the docs in the near future, it's not really important where this is placed at this time. Hopefully it's discoverable now that I've added the link in CONTRIBUTING.md.

**Pull request merged**
