### PR TITLE
WOF Venues Import Details

### PR DESCRIPTION
**Pull request by dianashk**

### CODE REVIEW

**Comment by trescube** [comment]
:shipit:

**Comment by orangejulius** [comment]
LGTM

**Comment by dianashk** [comment]
:shipit:

**Comment by trescube** [comment]
You're approving of your own PR?  Bold move.

**Comment by dianashk** [comment]
Sometimes you just have to pat yourself on the back, you know?!

**Comment by trescube** [comment]
👍

**Pull request merged**
