### PR TITLE
Add fun facts page

### PR DESCRIPTION
**Pull request by dianashk**
:wave: I did some awesome work for the Pelias project and would love for everyone to have a look at it and provide feedback.

---
#### Here's the reason for this change :rocket:
I thought we should have a place where we collect all the interesting things we learn about along the way.

---
#### Here's what actually got changed :clap:
Added a menu item on the left and the actual page in markdown.

---
#### Here's how others can test the changes :eyes:
Check out the precog link in the github hooks area.

### CODE REVIEW

**Comment by missinglink** [comment]
https://en.wikipedia.org/wiki/Agloe,_New_York

**Comment by missinglink** [comment]
https://en.wikipedia.org/wiki/Circleville,_Ohio

> Dissatisfaction among residents rose over Circleville's layout, however. In 1837 at the request of the town, the Ohio General Assembly authorized the "Circleville Squaring Company" to convert the town plan into a squared grid, as was typical of other platted towns.

**Comment by missinglink** [comment]
http://www.cntraveler.com/story/why-pheasant-island-is-sometimes-in-france-sometimes-in-spain

**Comment by missinglink** [comment]
http://interestingengineering.com/16-of-the-most-stunning-international-borders/

**Comment by orangejulius** [comment]
[Carmel-by-the-Sea](http://www.carmelcalifornia.com/fun-facts-about-carmel.htm?PageSpeed=noscript): no addresses, no ice cream, no high heels

**Pull request merged**
