### PR TITLE
Added list of former team members + Waffle as meta-issue tracker

### PR DESCRIPTION
**Pull request by riordan**
Should really aggregate all of those into a contributors.md file to include all contributors to our source.

### CODE REVIEW

**Comment by mjcunningham** [comment]
Harish is hkrishna not harishk

**Comment by riordan** [comment]
Good catch!

On Thu, Oct 15, 2015 at 12:59 PM, Mike Cunningham <notifications@github.com>
wrote:

> Harish is hkrishna not harishk
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/pelias/pull/154#issuecomment-148456761>.
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>

**Comment by hkrishna** [comment]
YASSSSS! :+1:

**Comment by riordan** [comment]
@hkrishna missed you buddy

**Comment by orangejulius** [comment]
This is good. let's merge

**Comment by dianashk** [comment]
:shipit:

**Pull request merged**
